export * from "./DishCard"
export * from "./DishList"
export * from "./DishDetails"
export * from "./DishDetailsHeader"
export * from "./DishdetailsFooter"
export * from "./DishDetailsOrigin"
export * from "./DishDetailsIngredients"